In [25]:
%load_ext autoreload
%autoreload 2
import torch
from torch import nn
import numpy as np
import toolkit

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [26]:
data = np.sin(np.arange(200) * 0.1).reshape(-1, 1)
train = data[:150]
test = data[150:]

In [27]:
test

array([[ 0.65028784],
       [ 0.57119687],
       [ 0.48639869],
       [ 0.39674057],
       [ 0.30311836],
       [ 0.20646748],
       [ 0.10775365],
       [ 0.00796318],
       [-0.09190685],
       [-0.19085858],
       [-0.28790332],
       [-0.38207142],
       [-0.47242199],
       [-0.55805227],
       [-0.63810668],
       [-0.71178534],
       [-0.77835208],
       [-0.83714178],
       [-0.88756703],
       [-0.92912401],
       [-0.96139749],
       [-0.98406501],
       [-0.99690007],
       [-0.99977443],
       [-0.99265938],
       [-0.97562601],
       [-0.9488445 ],
       [-0.91258245],
       [-0.86720218],
       [-0.81315711],
       [-0.75098725],
       [-0.68131377],
       [-0.60483282],
       [-0.52230859],
       [-0.43456562],
       [-0.34248062],
       [-0.24697366],
       [-0.14899903],
       [-0.04953564],
       [ 0.05042269],
       [ 0.14987721],
       [ 0.24783421],
       [ 0.34331493],
       [ 0.43536536],
       [ 0.52306577],
       [ 0

In [28]:
seq_len = 10
x_train, y_train = toolkit.create_sequence(train, seq_len)
x_test, y_test = toolkit.create_sequence(test, seq_len)

In [29]:
x_test

array([[[ 0.65028784],
        [ 0.57119687],
        [ 0.48639869],
        [ 0.39674057],
        [ 0.30311836],
        [ 0.20646748],
        [ 0.10775365],
        [ 0.00796318],
        [-0.09190685],
        [-0.19085858]],

       [[ 0.57119687],
        [ 0.48639869],
        [ 0.39674057],
        [ 0.30311836],
        [ 0.20646748],
        [ 0.10775365],
        [ 0.00796318],
        [-0.09190685],
        [-0.19085858],
        [-0.28790332]],

       [[ 0.48639869],
        [ 0.39674057],
        [ 0.30311836],
        [ 0.20646748],
        [ 0.10775365],
        [ 0.00796318],
        [-0.09190685],
        [-0.19085858],
        [-0.28790332],
        [-0.38207142]],

       [[ 0.39674057],
        [ 0.30311836],
        [ 0.20646748],
        [ 0.10775365],
        [ 0.00796318],
        [-0.09190685],
        [-0.19085858],
        [-0.28790332],
        [-0.38207142],
        [-0.47242199]],

       [[ 0.30311836],
        [ 0.20646748],
        [ 0.10775365],
   

In [30]:
input_size = 1
hidden_size = 32
num_layer = 2
out_size = 1

model = toolkit.LSTM(input_size, hidden_size, num_layer, out_size)

In [31]:
model

LSTM(
  (lstm): LSTM(1, 32, num_layers=2, batch_first=True)
  (fc): Linear(in_features=32, out_features=1, bias=True)
)

In [32]:
epochs = 100
learning_rate = 0.01
batch_size = 16

x_train = torch.from_numpy(x_train).float()
y_train = torch.from_numpy(y_train).float()

criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

for epoch in range(epochs):
    loss_train = 0
    model.train()
    for i in range(0, len(x_train), batch_size):
        input_ = x_train[i:i + batch_size]
        target_ = y_train[i:i + batch_size]

        outputs = model(input_)
        loss = criterion(outputs, target_)
        loss_train += loss
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    
    if epoch % 10 == 0:
        loss_train /= (len(x_train)//batch_size)
        print(f"Epoch {epoch} | loss: {loss_train:.6f}")

Epoch 0 | loss: 0.537770
Epoch 10 | loss: 0.004990
Epoch 20 | loss: 0.000397
Epoch 30 | loss: 0.000458
Epoch 40 | loss: 0.000872
Epoch 50 | loss: 0.000218
Epoch 60 | loss: 0.001007
Epoch 70 | loss: 0.000230
Epoch 80 | loss: 0.011579
Epoch 90 | loss: 0.000037


In [34]:
x_train[0]

tensor([[0.0000],
        [0.0998],
        [0.1987],
        [0.2955],
        [0.3894],
        [0.4794],
        [0.5646],
        [0.6442],
        [0.7174],
        [0.7833]])