In [1]:
import numpy as np
from scipy import sparse

CSC - Compressed Sparse Column. For efficient arithmetic, fast column slicing.

CSR - Compressed Sparse Row. For fast row slicing, faster matrix vector products

In [2]:
arr = np.array([0, 0, 0, 0, 0, 1, 1, 0, 2])
print(sparse.csr_matrix(arr))
"""The 1. item is in row 0 position 5 and has the value 1.

The 2. item is in row 0 position 6 and has the value 1.

The 3. item is in row 0 position 8 and has the value 2."""

  (0, 5)	1
  (0, 6)	1
  (0, 8)	2


'The 1. item is in row 0 position 5 and has the value 1.\n\nThe 2. item is in row 0 position 6 and has the value 1.\n\nThe 3. item is in row 0 position 8 and has the value 2.'

In [3]:
arr = np.array([[0, 0, 0], [0, 0, 1], [1, 0, 2]])

print(sparse.csr_matrix(arr).data)
"""Viewing stored data (not the zero items) with the data property:"""

[1 1 2]


'Viewing stored data (not the zero items) with the data property:'

In [4]:
arr = np.array([[0, 0, 0], [0, 0, 1], [1, 0, 2]])
"""Counting nonzeros with the count_nonzero() method:"""
print(sparse.csr_matrix(arr).count_nonzero())

3


In [5]:
"""Removing zero-entries from the matrix with the eliminate_zeros() method:"""
arr = np.array([[0, 0, 0], [0, 0, 1], [1, 0, 2]])

mat = sparse.csr_matrix(arr)
mat.eliminate_zeros()
print(arr)
print(mat)

[[0 0 0]
 [0 0 1]
 [1 0 2]]
  (1, 2)	1
  (2, 0)	1
  (2, 2)	2


In [6]:
"""Eliminating duplicate entries with the sum_duplicates() method:"""
import numpy as np
from scipy.sparse import csr_matrix

arr = np.array([[0, 0, 0], [0, 0, 1], [1, 0, 2]])

mat = csr_matrix(arr)
mat.sum_duplicates()

print(mat)

  (1, 2)	1
  (2, 0)	1
  (2, 2)	2


In [7]:
"""Converting from csr to csc with the tocsc() method:"""
import numpy as np
from scipy.sparse import csr_matrix

arr = np.array([[0, 0, 0], [0, 0, 1], [1, 0, 2]])

newarr = csr_matrix(arr).tocsc()

print(newarr)

  (2, 0)	1
  (1, 2)	1
  (2, 2)	2
