# Example

In [89]:
import torch
import numpy as np

data = np.array([[1.0, 2.0, 3.0],
                 [4.0, 5.0, 6.0],
                 [7.0, 8.0, 9.0]])
data_shape = data.shape

# MinMaxScaler Normal

In [56]:
# Min-max scaling
min_val = data.min()
max_val = data.max()
scaled_data = (data - min_val) / (max_val - min_val)

print("Scaled Data (MinMaxScaler):\n", scaled_data)


Scaled Data (MinMaxScaler):
 [[0.    0.125 0.25 ]
 [0.375 0.5   0.625]
 [0.75  0.875 1.   ]]


# MinMaxScaler - sklearn
X_std = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))

X_scaled = X_std * (max - min) + min

In [57]:
from sklearn.preprocessing import MinMaxScaler

# Create MinMaxScaler object
scaler = MinMaxScaler(feature_range=(0.0, 1.0))

# Fit the scaler to the data and transform the data
scaled_data = scaler.fit_transform(data.reshape(-1, 1)).reshape(data_shape)

print("Original Data:\n", data)
print("\nScaled Data (MinMaxScaler):\n", scaled_data)

Original Data:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

Scaled Data (MinMaxScaler):
 [[0.    0.125 0.25 ]
 [0.375 0.5   0.625]
 [0.75  0.875 1.   ]]


# StandardScaler
The standard score of a sample x is calculated as:

z = (x - u) / s

where u is the mean of the training samples or zero if with_mean=False, and s is the standard deviation of the training samples or one if with_std=False.

In [58]:
mean = data.mean()
std_dev = data.std()
standardized_data = (data - mean) / std_dev

print("Standardized Data (StandardScaler):\n", standardized_data)


Standardized Data (StandardScaler):
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [59]:
from sklearn.preprocessing import StandardScaler
data_n = data.reshape(-1, 1)

scaler = StandardScaler()
scaler.fit(data_n)
scaler.transform(data_n).reshape(data_shape)

array([[-1.54919334, -1.161895  , -0.77459667],
       [-0.38729833,  0.        ,  0.38729833],
       [ 0.77459667,  1.161895  ,  1.54919334]])

# RobustScaler

In [62]:
from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()
scaler.fit_transform(data.reshape(-1, 1)).reshape(data_shape)

array([[-1.  , -0.75, -0.5 ],
       [-0.25,  0.  ,  0.25],
       [ 0.5 ,  0.75,  1.  ]])

# MaxAbsScaler

In [63]:
from sklearn.preprocessing import MaxAbsScaler
scaler = MaxAbsScaler()
scaler.fit_transform(data.reshape(-1, 1)).reshape(data_shape)

array([[0.11111111, 0.22222222, 0.33333333],
       [0.44444444, 0.55555556, 0.66666667],
       [0.77777778, 0.88888889, 1.        ]])

# PowerTransformer

In [69]:
from sklearn.preprocessing import PowerTransformer
scaler = PowerTransformer(method="box-cox")
scaler.fit_transform(data.reshape(-1, 1)).reshape(data_shape)


array([[-1.69300617, -1.16788746, -0.71478085],
       [-0.30290105,  0.08080817,  0.44346554],
       [ 0.78950339,  1.12192248,  1.44287594]])

# QuantileTransformer

In [73]:
from sklearn.preprocessing import QuantileTransformer
scaler = QuantileTransformer(n_quantiles=5, random_state=42)
scaler.fit_transform(data.reshape(-1, 1)).reshape(data_shape)


array([[0.   , 0.125, 0.25 ],
       [0.375, 0.5  , 0.625],
       [0.75 , 0.875, 1.   ]])

# FunctionTransformer

In [88]:
from sklearn.preprocessing import FunctionTransformer

def tf(x):
    return x/len(x)

def tf_inverse(x):
    return x*len(x)

scaler = FunctionTransformer(func=tf, inverse_func=tf_inverse, validate=True)
scaler.fit_transform(data.reshape(-1, 1)).reshape(data_shape)

# scaler.transform(np.array([10, 11]).reshape(-1, 1))

array([[0.11111111, 0.22222222, 0.33333333],
       [0.44444444, 0.55555556, 0.66666667],
       [0.77777778, 0.88888889, 1.        ]])