In [2]:
import numpy as np


In [8]:
a = [1, 2, 3, 4]
b = [1, 2, 3, 4]
print(np.add(a, b))
print(a + b)

[2 4 6 8]
[1, 2, 3, 4, 1, 2, 3, 4]


# creat function

In [9]:
def myadd(x, y):
    return x + y


myadd = np.frompyfunc(myadd, 2, 1)
print(myadd([1, 2], [1, 2]))

[2 4]


# add

In [10]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

[30 32 34 36 38 40]


# subtraction

In [11]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

[-10  -1   8  17  26  35]


# multiplication

In [12]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

print(newarr)

[ 200  420  660  920 1200 1500]


# division

In [15]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([0, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)

print(newarr)

[        inf  4.          3.          5.         25.          1.81818182]


C:\Users\keipj\AppData\Local\Temp\ipykernel_15036\365774750.py:4: RuntimeWarning: divide by zero encountered in divide
  newarr = np.divide(arr1, arr2)


# power

In [16]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr)

[      1000    3200000  729000000 -520093696       2500          0]


# Reminder / mod

In [17]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.remainder(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]
[ 1  6  3  0  0 27]


# quotient and mod

In [18]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


# abs

In [19]:
arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

[1 2 1 2 3 4]


# rounding

In [20]:
arr = np.array([1.3324, 1.563, 1.5, 12.4])
print(np.trunc(arr))
print(np.fix(arr))


[ 1.  1.  1. 12.]
[ 1.  1.  1. 12.]


In [3]:
arr = np.around([10, 3.515, 3.5113])
print(arr)

[10.  4.  4.]


In [19]:
print(np.floor([2.34, 52.93, 0.2, 0.5]))
print(np.ceil([2.34, 52.93, 0.2, 0.5]))

[ 2. 52.  0.  0.]
[ 3. 53.  1.  1.]


# Log at Base 2

In [24]:
arr = np.arange(1, 10)
a = np.array([i for i in range(1, 10)])
print(a)

print(np.log2(arr))

[1 2 3 4 5 6 7 8 9]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


### Log at Base 10

In [25]:
arr = np.arange(1, 10)

print(np.log10(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


## Log at Base e

In [26]:
arr = np.arange(1, 10)

print(np.log(arr))


[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


# Summation

In [31]:
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[1, 2, 3]])
arr3 = np.array([[3, 3, 3]])
arr4 = np.array([[10, -1, -1]])
newarr = np.sum([[arr1, arr2], [arr3, arr4]])

print(newarr)

29


In [41]:
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[1, 2, 3]])
arr3 = np.array([[3, 3, 3]])
arr4 = np.array([[10, -1, -1]])

newar = np.sum([[arr1, arr2], [arr3, arr4]], axis=2)
newarr = np.sum([arr1, arr2], axis=0)
print(newar)
print("####")
print(newarr)

[[[ 1  2  3]
  [ 1  2  3]]

 [[ 3  3  3]
  [10 -1 -1]]]
####
[[2 4 6]]


In [42]:
# Cummulative Sum
arr = np.array([1, 2, 3])

newarr = np.cumsum(arr)

print(newarr)

[1 3 6]


# Products

In [43]:
arr = np.array([1, 2, 3, 4])

x = np.prod(arr)

print(x)

24


In [44]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.prod([arr1, arr2])

print(x)

40320


In [47]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

newarr = np.prod([arr1, arr2], axis=1)

print(newarr)

[  24 1680]


In [48]:
arr = np.array([5, 6, 7, 8])

newarr = np.cumprod(arr)

print(newarr)

[   5   30  210 1680]


# Differences

In [49]:
arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr)

print(newarr)

[  5  10 -20]


In [50]:
arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr, n=2)

print(newarr)

[  5 -30]


# LCM (Lowest Common Multiple)

In [52]:
num1 = 4
num2 = 6

x = np.lcm(num1, num2)

print(x)

12


In [55]:
arr = np.array([3, 6, 9])

x = np.lcm.reduce(arr)

print(x)

18


In [56]:
arr = np.arange(1, 11)

x = np.lcm.reduce(arr)

print(x)

2520


# GCD (Greatest Common Denominator)

In [57]:
num1 = 6
num2 = 9

x = np.gcd(num1, num2)

print(x)

3


In [58]:
arr = np.array([20, 8, 32, 36, 16])

x = np.gcd.reduce(arr)

print(x)

4


In [59]:
x = np.sin(np.pi / 2)

print(x)

1.0


In [60]:
arr = np.array([np.pi / 2, np.pi / 3, np.pi / 4, np.pi / 5])

x = np.sin(arr)

print(x)

[1.         0.8660254  0.70710678 0.58778525]


In [61]:
arr = np.array([90, 180, 270, 360])

x = np.deg2rad(arr)

print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [62]:
arr = np.array([np.pi / 2, np.pi, 1.5 * np.pi, 2 * np.pi])

x = np.rad2deg(arr)

print(x)

[ 90. 180. 270. 360.]


In [64]:
x = np.arcsin(1.0)

print(x)
print(np.rad2deg(x))

1.5707963267948966
90.0


In [67]:
base = 3
perp = 4

x = np.hypot(base, perp)

print(x)

5.0


In [68]:
arr = np.array([np.pi / 2, np.pi / 3, np.pi / 4, np.pi / 5])

x = np.cosh(arr)

print(x)

[2.50917848 1.60028686 1.32460909 1.20397209]


In [69]:
arr = np.array([0.1, 0.2, 0.5])

x = np.arctanh(arr)

print(x)

[0.10033535 0.20273255 0.54930614]


# NumPy Set Operations

In [70]:
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)

[1 2 3 4 5 6 7]


In [71]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

print(newarr)

[1 2 3 4 5 6]


In [79]:
arr1 = np.array([1, 2, 3, 4, 1])
arr2 = np.array([3, 4, 5, 6, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=False)

print(newarr)
newarr = np.intersect1d(arr1, arr2, assume_unique=True)

print(newarr)

[3 4]
[1 3 4 6]


In [84]:
set1 = np.array([1, 2, 3, 4, 4, 1])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True)

print(newarr)

[1 2 1]


In [85]:
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setxor1d(set1, set2, assume_unique=True)

print(newarr)

[1 2 5 6]
