In [67]:
import pandas as pd

In [68]:
data_y_1 = pd.read_csv("raw-data/Non-Native-1.csv")
data_y_2 = pd.read_csv("raw-data/Non-Native-2.csv")
data_y_3 = pd.read_csv("raw-data/Non-Native-3.csv")
data_y_4 = pd.read_csv("raw-data/Non-Native-4.csv")

In [69]:
non_native = data_y_1.iloc[:, 1:-1].values + data_y_2.iloc[:, 1:].values + data_y_3.iloc[:, 1:].values + data_y_4.iloc[
                                                                                                         :, 1:].values

In [70]:
non_native = pd.DataFrame(non_native, index=[1394, 1395, 1396, 1397, 1398, 1399, 1400, 1401],
                          columns=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [71]:
non_native

1     2     3     4     5     6     7     8     9     10    11    12
1394  1664  2027  2186  1800  2216  2341  1971  2136  2182  2085  2272  2172
1395  2116  2688  2912  2387  2864  2563  2408  2608  2281  2386  2286  2210
1396  1828  2565  2347  2727  2945  2781  2532  2532  2556  2691  2725  2463
1397  2118  3040  2489  3488  3270  3067  3161  2781  2923  2976  2756  2781
1398  2163  3049  2904  3755  3224  3291  2946  2908  2838  2814  2807  1193
1399   569  1344  1925  2362  2414  2684  2354  1396  1403  2138  2297  2407
1400  1992  2122  3277  2873  2523  3178  3102  3420  3295  2938  2870  2780
1401  2319  2901  3933  3519  3583  3870  3162  3581  3570  3049  3122  3228

In [72]:
index = []
for y in range(1394,1402):
    for i in range(1,13):
        if len(str(i)) == 1:
            index.append(str(y)+"_0"+str(i))
        else:
            index.append(str(y)+"_"+str(i))
            
non_natives = []
b = 0
for i in non_native.values:
    for j in i:
        non_natives.append(j)
        

non_native = pd.DataFrame(non_natives, index=index, columns=["non_native"])
non_native.to_csv("data/data.csv")

# part 2

In [75]:
data_some = pd.read_csv("raw-data/some-data.csv")
data = non_native


In [76]:
data_some

year    beds  marakez behdashti   labs  active beds  working employee  \
0  1394  2107.0               83.0  290.0       1747.0            4665.0   
1  1395  2120.0               83.0  317.0       1756.0            4571.0   
2  1396  2307.0               82.0  338.0       1938.0            4662.0   
3  1397  2308.0               85.0  354.0       1896.0            4651.0   
4  1398  2308.0               87.0  372.0       1941.0            4677.0   
5  1399  2313.0               89.0  401.0       1901.0            4791.0   
6  1400  2313.0               89.0  424.0       1930.0            5614.0   
7  1401     NaN                NaN    NaN          NaN               NaN   

   number of doctors  Unnamed: 7  doctors pir   stuff  
0              545.0      2421.0       2421.0  1699.0  
1              606.0      2376.0       2376.0  1589.0  
2              607.0      2544.0       2544.0  1511.0  
3              658.0      2531.0       2531.0  1462.0  
4              693.0      2592.0       2592.0  1392.0  
5              740.0      2714.0       2714.0  1337.0  
6              790.0      3262.0       3262.0  1562.0  
7                NaN         NaN          NaN     NaN

In [77]:
beds = []
marakez_behdasht = []
labs = []
active_beds =[]
n_employee = []
n_doctors = []
n_doctors_pir = []
stuff = []
for i in data_some.values:
    for _ in range(12):
        beds.append(i[1])
        marakez_behdasht.append(i[2])
        labs.append(i[3])
        active_beds.append(i[4])
        n_employee.append(i[5])
        n_doctors.append(i[6])
        n_doctors_pir.append(i[8])
        stuff.append(i[9])
        

In [78]:
data_hotel = pd.read_csv("raw-data/hotel.csv")


In [79]:
hotel = []
b = 0
for i in data_hotel.iloc[:,1:].values:
    for j in i:
        hotel.append(j)
len(hotel)

96

In [80]:
data_travel_inside = pd.read_csv("raw-data/travel-person-inside.csv")
data_travel_outside = pd.read_csv("raw-data/travel-person-outside.csv")

In [81]:
data_travel_inside

سال   تعداد سفر   اتوبوس  مینی بوس   سواری   تعداد مسافر   اتوبوس.1  \
0  1394       12060    9496       1949     615        168981    155352   
1  1395       22714   12896       6783    3035        236641    214739   
2  1396       26611   12793      10508    3310        256651    228844   
3  1397       23860   12321       9053    2486        219801    196746   
4  1398       23660   11098       9543    3019        203867    179258   
5  1399       21219    9307       9020    2892        146638    130409   
6  1400       21719    9911       9468    2340        165911    153304   
7  1401       22829   11294       9487    2048        225067    208977   

   مینی بوس .1  سواری .1  
0        12874       755  
1        18385      3517  
2        23942      3865  
3        20403      2652  
4        21314      3295  
5        13206      3023  
6        10266      2341  
7        13863      2227

In [82]:
bus_travel_inside = []
mini_bus_travel_inside = []
car_travel_inside = []

bus_travel_outside = []
mini_bus_travel_outside = []
car_travel_outside = []

bus_person_travel_inside = []
mini_bus_person_travel_inside = []
car_person_travel_inside = []

bus_person_travel_outside = []
mini_bus_person_travel_outside = []
car_person_travel_outside = []


for i in data_travel_inside.values:
    print(i)
    print(i[2])
    print(i[3])
    print(i[4])
    print(i[6],[i[7],i[8]])
    for _ in range(12):
        bus_travel_inside.append(i[2])
        mini_bus_travel_inside.append(i[3])
        car_travel_inside.append(i[4])
        bus_person_travel_inside.append(i[6])
        mini_bus_person_travel_inside.append(i[7])
        car_person_travel_inside.append(i[8])

for i in data_travel_outside.values:
    for _ in range(12):
        bus_travel_outside.append(i[2])
        mini_bus_travel_outside.append(i[3])
        car_travel_outside.append(i[4])
        bus_person_travel_outside.append(i[6])
        mini_bus_person_travel_outside.append(i[7])
        car_person_travel_outside.append(i[8])
        
len(bus_travel_outside), len(bus_travel_inside)

[  1394  12060   9496   1949    615 168981 155352  12874    755]
9496
1949
615
155352 [12874, 755]
[  1395  22714  12896   6783   3035 236641 214739  18385   3517]
12896
6783
3035
214739 [18385, 3517]
[  1396  26611  12793  10508   3310 256651 228844  23942   3865]
12793
10508
3310
228844 [23942, 3865]
[  1397  23860  12321   9053   2486 219801 196746  20403   2652]
12321
9053
2486
196746 [20403, 2652]
[  1398  23660  11098   9543   3019 203867 179258  21314   3295]
11098
9543
3019
179258 [21314, 3295]
[  1399  21219   9307   9020   2892 146638 130409  13206   3023]
9307
9020
2892
130409 [13206, 3023]
[  1400  21719   9911   9468   2340 165911 153304  10266   2341]
9911
9468
2340
153304 [10266, 2341]
[  1401  22829  11294   9487   2048 225067 208977  13863   2227]
11294
9487
2048
208977 [13863, 2227]


(96, 96)

In [86]:
import numpy as np
values = np.array([non_natives, beds, marakez_behdasht, labs, active_beds, n_employee, n_doctors, n_doctors_pir, stuff, hotel, bus_travel_inside, bus_travel_outside, mini_bus_travel_inside, mini_bus_travel_outside, car_travel_inside, car_travel_outside, bus_person_travel_inside, bus_person_travel_outside, mini_bus_person_travel_inside, mini_bus_person_travel_outside, car_person_travel_inside, car_person_travel_outside]).transpose()

columns = ["y", "number_of_beds", "markaze_behdasht", "number_of_labs", "number_of_active_beds", "number_of_employees", "number_of_doctors", "number_of_pir_doctors", "number_of_stuff", "number_of_persons_in_hotels", "number_of_travels_bus_inside", "number_of_travels_bus_outside", "number_of_travels_minibus_inside", "number_of_travels_minibus_outside", "number_of_travels_car_inside", "number_of_travels_car_outside", "number_of_person_bus_inside", "number_of_person_bus_outside","number_of_person_minibus_inside", "number_of_person_minibus_outside", "number_of_person_car_inside", "number_of_person_car_outside"]

index = index

print(len(values))
print(len(columns))
print(len(index))

data = pd.DataFrame(values, index=index, columns=columns)
data

96
22
96


y  number_of_beds  markaze_behdasht  number_of_labs  \
1394_01  1664.0          2107.0              83.0           290.0   
1394_02  2027.0          2107.0              83.0           290.0   
1394_03  2186.0          2107.0              83.0           290.0   
1394_04  1800.0          2107.0              83.0           290.0   
1394_05  2216.0          2107.0              83.0           290.0   
...         ...             ...               ...             ...   
1401_08  3581.0             NaN               NaN             NaN   
1401_09  3570.0             NaN               NaN             NaN   
1401_10  3049.0             NaN               NaN             NaN   
1401_11  3122.0             NaN               NaN             NaN   
1401_12  3228.0             NaN               NaN             NaN   

         number_of_active_beds  number_of_employees  number_of_doctors  \
1394_01                 1747.0               4665.0              545.0   
1394_02                 1747.0               4665.0              545.0   
1394_03                 1747.0               4665.0              545.0   
1394_04                 1747.0               4665.0              545.0   
1394_05                 1747.0               4665.0              545.0   
...                        ...                  ...                ...   
1401_08                    NaN                  NaN                NaN   
1401_09                    NaN                  NaN                NaN   
1401_10                    NaN                  NaN                NaN   
1401_11                    NaN                  NaN                NaN   
1401_12                    NaN                  NaN                NaN   

         number_of_pir_doctors  number_of_stuff  number_of_persons_in_hotels  \
1394_01                 2421.0           1699.0                          NaN   
1394_02                 2421.0           1699.0                          NaN   
1394_03                 2421.0           1699.0                          NaN   
1394_04                 2421.0           1699.0                          NaN   
1394_05                 2421.0           1699.0                          NaN   
...                        ...              ...                          ...   
1401_08                    NaN              NaN                       9200.0   
1401_09                    NaN              NaN                       9225.0   
1401_10                    NaN              NaN                       9225.0   
1401_11                    NaN              NaN                       9238.0   
1401_12                    NaN              NaN                       9240.0   

         ...  number_of_travels_minibus_inside  \
1394_01  ...                            1949.0   
1394_02  ...                            1949.0   
1394_03  ...                            1949.0   
1394_04  ...                            1949.0   
1394_05  ...                            1949.0   
...      ...                               ...   
1401_08  ...                            9487.0   
1401_09  ...                            9487.0   
1401_10  ...                            9487.0   
1401_11  ...                            9487.0   
1401_12  ...                            9487.0   

         number_of_travels_minibus_outside  number_of_travels_car_inside  \
1394_01                              733.0                         615.0   
1394_02                              733.0                         615.0   
1394_03                              733.0                         615.0   
1394_04                              733.0                         615.0   
1394_05                              733.0                         615.0   
...                                    ...                           ...   
1401_08                             2312.0                        2048.0   
1401_09                             2312.0                        2048.0   
1401_10                             2312.0        

In [87]:
data.to_csv("data/data_complete.csv")