In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import DataLoader, Engine, Machine_Model
from pathlib import Path
import torch

torch.manual_seed(42)
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)
city = "luzern"

luzern_data = DataLoader.Dataloader()
data_path = Path("D:\All Python\All_Big_raw_Data\LOS prediction\Traffic Dataset\DataLoader")
data_path = data_path / city

BATCH_SIZE = 64

train_dataloader, val_dataloader, test_dataloader = luzern_data.create_dataloaders(data_dir=data_path, city_code=city,
                                                                                   batch_size=BATCH_SIZE)

INPUT_SIZE = 14  # number of features
HIDDEN_UNITS = 32
OUTPUT_SIZE = len(luzern_data.class_names)
EPOCHS = 500
model_name = f"LOS_predict_Luzern_NN_V0"

model0 = Machine_Model.LOS_Classification_V0(input_size=INPUT_SIZE, hidden_size=HIDDEN_UNITS, output_size=OUTPUT_SIZE)

loss_fn = torch.nn.CrossEntropyLoss()
learning_rate = 0.001
optimizer = torch.optim.Adam(model0.parameters(), learning_rate)

engine = Engine.Machine_Engine(model=model0, train_dataloader=train_dataloader, val_dataloader=val_dataloader,
                               test_dataloader=test_dataloader)
model0_results = engine.train(model_name=model_name, loss_fn=loss_fn, optimizer=optimizer, epochs_num=EPOCHS,
                              early_stop_patience=None, writer=True)

cuda
[INFO] create SummaryWriter saving to runs\LOS_predict_Luzern_NN_V0\epochs_500\2024-01-23-15


  0%|          | 0/500 [00:00<?, ?it/s]

Epoch 0 | train: Loss 15.139443 Accuracy 0.4831 | validation: Loss 5.856843 Accuracy 0.5078
Epoch 1 | train: Loss 2.901418 Accuracy 0.6146 | validation: Loss 1.526961 Accuracy 0.6250
Epoch 2 | train: Loss 1.143368 Accuracy 0.6576 | validation: Loss 1.073077 Accuracy 0.6797
Epoch 3 | train: Loss 0.784282 Accuracy 0.7025 | validation: Loss 0.904187 Accuracy 0.6094
Epoch 4 | train: Loss 0.611495 Accuracy 0.7546 | validation: Loss 0.657430 Accuracy 0.7578
Epoch 5 | train: Loss 0.557256 Accuracy 0.7708 | validation: Loss 0.636939 Accuracy 0.7578
Epoch 6 | train: Loss 0.501485 Accuracy 0.7904 | validation: Loss 0.668341 Accuracy 0.7422
Epoch 7 | train: Loss 0.464146 Accuracy 0.8118 | validation: Loss 0.468423 Accuracy 0.8125
Epoch 8 | train: Loss 0.464155 Accuracy 0.7969 | validation: Loss 0.609936 Accuracy 0.7266
Epoch 9 | train: Loss 0.446349 Accuracy 0.7949 | validation: Loss 0.499919 Accuracy 0.8047
Epoch 10 | train: Loss 0.409191 Accuracy 0.8242 | validation: Loss 0.518682 Accuracy 0.78

In [3]:
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

true_labels = np.concatenate(engine.train_true_predict_list["true"])
predicted_labels = np.concatenate(engine.train_true_predict_list["predict"])

cm = confusion_matrix(true_labels, predicted_labels)
report = classification_report(true_labels, predicted_labels, zero_division=1)
print(cm)
print(report)
test_loss, test_acc, test_true_pred = engine.test(loss_fn=loss_fn)
print(test_acc)

[[439180   1576    204     57     32     97]
 [  2395  50315   3759    185     27      3]
 [   140   3264  89039   5118     53      0]
 [   199    333   3436 130113   2487      0]
 [    82     90     51   3193  32572      0]
 [     0      0      0      0      0      0]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99    441146
           1       0.91      0.89      0.90     56684
           2       0.92      0.91      0.92     97614
           3       0.94      0.95      0.95    136568
           4       0.93      0.91      0.92     35988
           5       0.00      1.00      0.00         0

    accuracy                           0.97    768000
   macro avg       0.78      0.94      0.78    768000
weighted avg       0.97      0.97      0.97    768000

[!!!IMPORTANT NOTE!!!]
The test_function provided here is intended solely for the final model analysis and reporting purposes.
Please refrain from using it as a general-purpose function 

In [7]:
test_acc*len(engine.val_dataloader)/len(engine.test_dataloader)

0.953125

In [8]:
import DataLoader, Engine, Machine_Model
from pathlib import Path
import torch

torch.manual_seed(42)
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)
city = "luzern"

luzern_data = DataLoader.Dataloader()
data_path = Path("D:\All Python\All_Big_raw_Data\LOS prediction\Traffic Dataset\DataLoader")
data_path = data_path / city

BATCH_SIZE = 64

train_dataloader, val_dataloader, test_dataloader = luzern_data.create_dataloaders(data_dir=data_path, city_code=city,
                                                                                   batch_size=BATCH_SIZE)

INPUT_SIZE = 14  # number of features
HIDDEN_UNITS = 32
OUTPUT_SIZE = len(luzern_data.class_names)
EPOCHS = 500
model_name = f"LOS_predict_Luzern_NN_V1"  #1 here

model1 = Machine_Model.LOS_Classification_V1(input_size=INPUT_SIZE, hidden_size=HIDDEN_UNITS,
                                             output_size=OUTPUT_SIZE)  #2 here

loss_fn = torch.nn.CrossEntropyLoss()
learning_rate = 0.001
optimizer = torch.optim.Adam(model1.parameters(), learning_rate)  #1 here

engine1 = Engine.Machine_Engine(model=model1, train_dataloader=train_dataloader, val_dataloader=val_dataloader,
                                test_dataloader=test_dataloader)  #2 here
model1_results = engine1.train(model_name=model_name, loss_fn=loss_fn, optimizer=optimizer, epochs_num=EPOCHS,
                               early_stop_patience=None, writer=True)  #2 here

cuda
[INFO] create SummaryWriter saving to runs\LOS_predict_Luzern_NN_V1\epochs_500\2024-01-23-16


  0%|          | 0/500 [00:00<?, ?it/s]

Epoch 0 | train: Loss 20.761736 Accuracy 0.3991 | validation: Loss 7.362779 Accuracy 0.5547
Epoch 1 | train: Loss 6.494722 Accuracy 0.4811 | validation: Loss 2.041655 Accuracy 0.6484
Epoch 2 | train: Loss 3.416737 Accuracy 0.5573 | validation: Loss 1.418442 Accuracy 0.6641
Epoch 3 | train: Loss 2.426435 Accuracy 0.5879 | validation: Loss 1.108987 Accuracy 0.6641
Epoch 4 | train: Loss 1.911221 Accuracy 0.6354 | validation: Loss 1.130512 Accuracy 0.6953
Epoch 5 | train: Loss 1.555358 Accuracy 0.6348 | validation: Loss 0.897126 Accuracy 0.6719
Epoch 6 | train: Loss 1.392506 Accuracy 0.6471 | validation: Loss 0.894820 Accuracy 0.6484
Epoch 7 | train: Loss 1.218901 Accuracy 0.6432 | validation: Loss 0.693361 Accuracy 0.7109
Epoch 8 | train: Loss 1.117877 Accuracy 0.6615 | validation: Loss 0.771670 Accuracy 0.6797
Epoch 9 | train: Loss 0.956441 Accuracy 0.6823 | validation: Loss 0.652121 Accuracy 0.7500
Epoch 10 | train: Loss 0.867602 Accuracy 0.7012 | validation: Loss 0.618217 Accuracy 0.71

In [9]:
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

true_labels = np.concatenate(engine1.train_true_predict_list["true"])
predicted_labels = np.concatenate(engine1.train_true_predict_list["predict"])

cm1 = confusion_matrix(true_labels, predicted_labels)
report1 = classification_report(true_labels, predicted_labels, zero_division=1)
print(cm1)
print(report1)
test_loss1, test_acc1, test_true_pred1 = engine1.test(loss_fn=loss_fn)
print(test_acc1)

[[437462   2234    526    565    167    192]
 [  4622  45182   6164    612     82     22]
 [   822   5432  81162   9801    348     49]
 [   603    600   6845 122393   6067     60]
 [   123    165    175   5465  30042     18]
 [     0      0      0      0      0      0]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99    441146
           1       0.84      0.80      0.82     56684
           2       0.86      0.83      0.84     97614
           3       0.88      0.90      0.89    136568
           4       0.82      0.83      0.83     35988
           5       0.00      1.00      0.00         0

    accuracy                           0.93    768000
   macro avg       0.73      0.89      0.73    768000
weighted avg       0.93      0.93      0.93    768000

[!!!IMPORTANT NOTE!!!]
The test_function provided here is intended solely for the final model analysis and reporting purposes.
Please refrain from using it as a general-purpose function 

In [10]:
import DataLoader, Engine, Machine_Model
from pathlib import Path
import torch

torch.manual_seed(42)
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)
city = "luzern"

luzern_data = DataLoader.Dataloader()
data_path = Path("D:\All Python\All_Big_raw_Data\LOS prediction\Traffic Dataset\DataLoader")
data_path = data_path / city

BATCH_SIZE = 64

train_dataloader, val_dataloader, test_dataloader = luzern_data.create_dataloaders(data_dir=data_path, city_code=city,
                                                                                   batch_size=BATCH_SIZE)

INPUT_SIZE = 14  # number of features
HIDDEN_UNITS = 32
OUTPUT_SIZE = len(luzern_data.class_names)
EPOCHS = 500
model_name = f"LOS_predict_Luzern_NN_V2"  #1 here

model2 = Machine_Model.LOS_Classification_V2(input_size=INPUT_SIZE, hidden_size=HIDDEN_UNITS,
                                             output_size=OUTPUT_SIZE)  #2 here

loss_fn = torch.nn.CrossEntropyLoss()
learning_rate = 0.001
optimizer = torch.optim.Adam(model2.parameters(), learning_rate)  #1 here

engine2 = Engine.Machine_Engine(model=model2, train_dataloader=train_dataloader, val_dataloader=val_dataloader,
                                test_dataloader=test_dataloader)  #2 here
model2_results = engine2.train(model_name=model_name, loss_fn=loss_fn, optimizer=optimizer, epochs_num=EPOCHS,
                               early_stop_patience=None, writer=True)  #2 here

cuda
[INFO] create SummaryWriter saving to runs\LOS_predict_Luzern_NN_V2\epochs_500\2024-01-23-16


  0%|          | 0/500 [00:00<?, ?it/s]

Epoch 0 | train: Loss 4.449535 Accuracy 0.6419 | validation: Loss 1.591310 Accuracy 0.6250
Epoch 1 | train: Loss 0.902442 Accuracy 0.7318 | validation: Loss 0.752688 Accuracy 0.6797
Epoch 2 | train: Loss 0.603631 Accuracy 0.7533 | validation: Loss 0.680251 Accuracy 0.7109
Epoch 3 | train: Loss 0.526888 Accuracy 0.7943 | validation: Loss 0.569059 Accuracy 0.7578
Epoch 4 | train: Loss 0.463247 Accuracy 0.8132 | validation: Loss 0.482070 Accuracy 0.8047
Epoch 5 | train: Loss 0.408535 Accuracy 0.8451 | validation: Loss 0.446323 Accuracy 0.7969
Epoch 6 | train: Loss 0.363109 Accuracy 0.8763 | validation: Loss 0.415364 Accuracy 0.8516
Epoch 7 | train: Loss 0.321018 Accuracy 0.8880 | validation: Loss 0.378192 Accuracy 0.8672
Epoch 8 | train: Loss 0.288870 Accuracy 0.9043 | validation: Loss 0.297197 Accuracy 0.8984
Epoch 9 | train: Loss 0.268015 Accuracy 0.9095 | validation: Loss 0.299869 Accuracy 0.8672
Epoch 10 | train: Loss 0.240371 Accuracy 0.9238 | validation: Loss 0.236432 Accuracy 0.906

In [11]:
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

true_labels = np.concatenate(engine2.train_true_predict_list["true"])
predicted_labels = np.concatenate(engine2.train_true_predict_list["predict"])

cm2 = confusion_matrix(true_labels, predicted_labels)
report2 = classification_report(true_labels, predicted_labels, zero_division=1)
print(cm2)
print(report2)
test_loss2, test_acc2, test_true_pred2 = engine2.test(loss_fn=loss_fn)
print(test_acc2)

[[439752   1350     27     60      7]
 [  1862  51792   2914     86      7]
 [    99   2838  90570   4065     21]
 [    76     69   3051 130995   2371]
 [    20     16      5   3229  32718]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    441196
           1       0.92      0.91      0.92     56661
           2       0.94      0.93      0.93     97593
           3       0.95      0.96      0.95    136562
           4       0.93      0.91      0.92     35988

    accuracy                           0.97    768000
   macro avg       0.95      0.94      0.94    768000
weighted avg       0.97      0.97      0.97    768000

[!!!IMPORTANT NOTE!!!]
The test_function provided here is intended solely for the final model analysis and reporting purposes.
Please refrain from using it as a general-purpose function in your own projects. Always refer to
the appropriate train and validation data for developing and fine-tuning your own models.
0.9479

In [20]:
max(model0_results["val_acc"])

1.0

In [26]:
print(max(model0_results["val_acc"][480:]))
print(max(model1_results["val_acc"][480:]))
print(max(model2_results["val_acc"][480:]))

0.9921875
0.9921875
0.984375
